handler: lambdas/request-amz-stock-update/request-amz-stock-update.handler
name: request-amz-stock-update
timeout: 30
role: RequestAmzListingReportRole
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/request-amz-stock-update/request-amz-stock-update.js
    - lambdas/request-amz-stock-update/helpers/**
    - lambdas/request-amz-stock-update/marketplaces.js
environment:
  MWS_KEY_ID: ${env:MWS_KEY_ID}
  MWS_KEY_SECRET: ${env:MWS_KEY_SECRET}
  AMZ_EU_SELLER_ID: ${env:AMZ_EU_SELLER_ID}
  AMZ_REPORT_QUEUE_URL: ${env:AMZ_REPORT_QUEUE_URL}
events:
  - http:
      method: get
      path: amz/request-update
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
  - schedule:
      rate: cron(0 7 ? * * *)
      enabled: true
      