service:
  name: kaskadi-stocks-api

plugins:
  - serverless-aws-documentation

custom:
  documentation:
    api:
      info:
        version: 0.0.1
        title: ${self:service.name}
        description: This API manages stocks for the Kaskadi project

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket

resources:
  Resources:
    RestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service.name}
    AmzResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref RestApi
            ParentId: !GetAtt RestApi.RootResourceId
            PathPart: "amz"
    YswsResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref RestApi
            ParentId: !GetAtt RestApi.RootResourceId
            PathPart: "ysws"
    CognitoAuthorizer:
      DependsOn:
        - RestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: RestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - !ImportValue KaskadiCognitoUserPoolARN

  Outputs:
    RestApiId:
      Value:
        Ref: RestApi
      Export:
        Name: ${self:service.name}-id
    RestApiRootResourceId:
      Value: !GetAtt RestApi.RootResourceId
      Export:
        Name: ${self:service.name}-root-resource-id
    AmzResourceId:
      Value:
        Ref: AmzResource
      Export:
        Name: ${self:service.name}-amz-resource-id
    YswsResourceId:
      Value:
        Ref: YswsResource
      Export:
        Name: ${self:service.name}-ysws-resource-id
    CognitoAuthorizerId:
      Value:
        Ref: CognitoAuthorizer
      Export:
        Name: ${self:service.name}-cognito-authorizer-id
