handler: lambdas/request-klima-stock-update/request-klima-stock-update.handler
name: ${self:service.name}-request-klima-stock-update-lambda
timeout: 30000
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/request-klima-stock-update/request-klima-stock-update.js
    - lambdas/request-klima-stock-update/helpers/**
    - lambdas/request-klima-stock-update/node_modules/**
environment:
  CMX_CLIENT_USER: ${env:CMX_CLIENT_USER}
  CMX_CLIENT_PWD: ${env:CMX_CLIENT_PWD}
  CMX_CUST_ID: ${env:CMX_CUST_ID}
events:
  - http:
      method: get
      path: klima/request-update
      cors: true
