handler: lambdas/request-klima-stock-update/request-klima-stock-update.handler
name: request-klima-stock-update
timeout: 30
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/request-klima-stock-update/request-klima-stock-update.js
    - lambdas/request-klima-stock-update/helpers/**
    - lambdas/request-klima-stock-update/node_modules/**
environment:
  CMX_CLIENT_USER: ${env:CMX_CLIENT_USER}
  CMX_CLIENT_PWD: ${env:CMX_CLIENT_PWD}
  CMX_CUST_ID: ${env:CMX_CUST_ID}
events:
  - http:
      method: get
      path: klima/request-update
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
  - schedule:
      rate: cron(0 7 ? * * *)
      enabled: true