name: deploy
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'serverless.json'
      - 'layer/**'
      - 'lambdas/**'
      - 'resources/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: serverless check
      uses: serverless/github-action@master
      with:
        args: deploy --noDeploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        CMX_CLIENT_USER: ${{ secrets.CMX_CLIENT_USER }}
        CMX_CLIENT_PWD: ${{ secrets.CMX_CLIENT_PWD }}
        CMX_CUST_ID: ${{ secrets.CMX_CUST_ID }}
        MWS_KEY_ID: ${{ secrets.MWS_KEY_ID }}
        MWS_KEY_SECRET: ${{ secrets.MWS_KEY_SECRET }}
        AMZ_EU_SELLER_ID: ${{ secrets.AMZ_EU_SELLER_ID }}
        COGNITO_USER_POOL_ARN: ${{ secrets.COGNITO_USER_POOL_ARN }}
        STOCKS_BUS_ARN: ${{ secrets.EB_STOCKS_BUS_ARN }}
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy -v
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        CMX_CLIENT_USER: ${{ secrets.CMX_CLIENT_USER }}
        CMX_CLIENT_PWD: ${{ secrets.CMX_CLIENT_PWD }}
        CMX_CUST_ID: ${{ secrets.CMX_CUST_ID }}
        MWS_KEY_ID: ${{ secrets.MWS_KEY_ID }}
        MWS_KEY_SECRET: ${{ secrets.MWS_KEY_SECRET }}
        AMZ_EU_SELLER_ID: ${{ secrets.AMZ_EU_SELLER_ID }}
        COGNITO_USER_POOL_ARN: ${{ secrets.COGNITO_USER_POOL_ARN }}
        STOCKS_BUS_ARN: ${{ secrets.EB_STOCKS_BUS_ARN }}
