name: deploy
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'serverless.json'
      - 'layer/**'
      - 'lambdas/**'
      - 'resources/**'
      - 'docs/**'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
  CMX_CLIENT_USER: ${{ secrets.CMX_CLIENT_USER }}
  CMX_CLIENT_PWD: ${{ secrets.CMX_CLIENT_PWD }}
  CMX_CUST_ID: ${{ secrets.CMX_CUST_ID }}
  MWS_KEY_ID: ${{ secrets.MWS_KEY_ID }}
  MWS_KEY_SECRET: ${{ secrets.MWS_KEY_SECRET }}
  AMZ_EU_SELLER_ID: ${{ secrets.AMZ_EU_SELLER_ID }}
  COGNITO_USER_POOL_ARN: ${{ secrets.COGNITO_USER_POOL_ARN }}
  STOCKS_BUS_ARN: ${{ secrets.EB_STOCKS_BUS_ARN }}
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v2
      with:
        git_user_signingkey: true
        git_commit_gpgsign: true
      env:
        GPG_PRIVATE_KEY: ${{ secrets.KASKADI_BOT_GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.KASKADI_BOT_GPG_PRIVATE_PASSPHRASE }}
    - name: Generate documentation
      uses: kaskadi/action-generate-docs@master
      with:
        type: api
        template: docs/template.md
  deploy:
    runs-on: ubuntu-latest
    needs: generate-docs
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Pull latest commit
      run: |
        git config pull.rebase false
        git pull
    - name: Install dependencies
      run: npm i
    - name: serverless check
      uses: serverless/github-action@master
      with:
        args: deploy --noDeploy
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy -v
