# ATTENTION: no deployment should be done until serverless.yml is properly setup
name: deploy
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'serverless.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    # uncomment section below to enable pre deployment testing
    # - name: serverless-check
    #   uses: kaskadi/action-slscli@master
    #   with:
    #     command: 'deploy --noDeploy'
    #     should_throw: true
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
    #     SLS_DEPLOY_BUCKET: ${{ secrets.SLS_DEPLOY_BUCKET }}
    - name: serverless-deploy
      uses: kaskadi/action-slscli@master
      with:
        command: '--version'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        SLS_DEPLOY_BUCKET: ${{ secrets.SLS_DEPLOY_BUCKET }}
